/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a GitHub OAuth authorization code for a Kyndro API token. */
        post: operations["exchangeGithubCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identity of the caller behind the presented bearer token. */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List repositories connected to the caller's account. */
        get: operations["listRepos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List verification runs, newest first. */
        get: operations["listRuns"];
        put?: never;
        /** Trigger a verification run for a commit range. */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one run with its analysis summary. */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/obligations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the obligations produced by a run. */
        get: operations["listRunObligations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/specs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List candidate and accepted specs. */
        get: operations["listSpecs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Repo identifier — `repo_` + 26-char Crockford-base32 ULID (ADR-001). */
        RepoId: string;
        /** @description Run identifier (ADR-001). */
        RunId: string;
        /** @description Obligation identifier (ADR-001). */
        ObligationId: string;
        /** @description Spec identifier (ADR-001). */
        SpecId: string;
        /** @description Counterexample identifier (ADR-001). */
        CounterexampleId: string;
        /** @description User identifier (ADR-001). */
        UserId: string;
        /** @description Full 40-character git commit SHA. */
        GitSha: string;
        /**
         * Format: date-time
         * @description RFC 3339 UTC timestamp.
         */
        Timestamp: string;
        /** @description Cursor for the next page, or null when this is the last page (ADR-002). */
        NextCursor: string | null;
        ErrorEnvelope: {
            error: {
                /** @description Stable machine-readable code, SCREAMING_SNAKE_CASE. */
                code: string;
                /** @description Human-readable explanation. Not stable; do not parse. */
                message: string;
                /** @description Optional structured context (field errors, ids). */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        AuthSession: {
            token: {
                /** @description Opaque bearer token. Store securely; never logged. */
                access_token: string;
                /** @constant */
                token_type: "bearer";
                expires_at: components["schemas"]["Timestamp"];
            };
            user: components["schemas"]["User"];
        };
        User: {
            id: components["schemas"]["UserId"];
            /** @description GitHub username of the authenticated user. */
            github_login: string;
            display_name?: string | null;
            /** Format: uri */
            avatar_url?: string | null;
            created_at: components["schemas"]["Timestamp"];
        };
        Repo: {
            id: components["schemas"]["RepoId"];
            /** @description GitHub org or user that owns the repository. */
            owner: string;
            name: string;
            default_branch: string;
            /**
             * @description suspended = GitHub App uninstalled or access revoked.
             * @enum {string}
             */
            status: "active" | "suspended";
            latest_run_id?: components["schemas"]["RunId"] | null;
            connected_at: components["schemas"]["Timestamp"];
        };
        /**
         * @description Run lifecycle. `failed` means the run itself errored (infrastructure, checkout, analysis crash) — it is NOT a verdict. Verdicts live on obligations.
         *
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "completed" | "failed";
        /** @description Obligation tally by verdict. All zeros until execution starts. */
        VerdictCounts: {
            verified: number;
            falsified: number;
            unknown: number;
        };
        /** @description The pull request that triggered a run, when there is one. */
        PullRequestRef: {
            number: number;
            title: string;
            author_login: string;
            /** Format: uri */
            url?: string;
        };
        Run: {
            id: components["schemas"]["RunId"];
            repo_id: components["schemas"]["RepoId"];
            status: components["schemas"]["RunStatus"];
            /** @enum {string} */
            trigger: "pull_request" | "manual";
            pr?: components["schemas"]["PullRequestRef"] | null;
            head_sha: components["schemas"]["GitSha"];
            base_sha: components["schemas"]["GitSha"];
            obligation_count: number;
            verdict_counts: components["schemas"]["VerdictCounts"];
            created_at: components["schemas"]["Timestamp"];
            started_at: components["schemas"]["Timestamp"] | null;
            completed_at: components["schemas"]["Timestamp"] | null;
        };
        ChangedFunction: {
            /** @description Function or method name, `Class.method` for methods. */
            name: string;
            /** @description Path relative to the repository root. */
            file: string;
            /** @enum {string} */
            change_kind: "added" | "modified" | "removed";
        };
        /** @description A function that inherits obligations because it calls changed code. */
        BlastRadiusEntry: {
            name: string;
            file: string;
            /** @description Human-readable why, e.g. "calls applyDiscount". */
            reason: string;
        };
        /** @description Diff analysis summary attached to a run once analysis completes. */
        RunAnalysis: {
            files_changed: number;
            functions_changed: components["schemas"]["ChangedFunction"][];
            blast_radius: components["schemas"]["BlastRadiusEntry"][];
        };
        RunDetail: components["schemas"]["Run"] & {
            analysis: components["schemas"]["RunAnalysis"] | null;
        };
        /**
         * @description Exactly three verdict states. VERIFIED is always bounded verification and MUST carry BoundedVerification metadata. UNKNOWN is an honest, acceptable verdict.
         *
         * @enum {string}
         */
        Verdict: "VERIFIED" | "FALSIFIED" | "UNKNOWN";
        /** @description Evidence for a bounded VERIFIED verdict. */
        BoundedVerification: {
            /** @description Number of generated inputs executed against the property. */
            inputs_tested: number;
            /** @description PRNG seed — replaying with this seed reproduces the exact inputs. */
            seed: string;
            /** @description Human-readable description of the explored input domain, e.g. "quantities 0..1000, prices 0..10^6 cents, up to 50 cart lines".
             *      */
            bounds: string;
            duration_ms?: number;
        };
        /** @description Why the engine could not decide. Required when verdict is UNKNOWN. */
        UnknownReason: {
            /** @enum {string} */
            code: "unsupported_construct" | "timeout" | "external_effects" | "generator_unavailable";
            message: string;
        };
        CounterexampleInput: {
            /** @description Parameter name in the target function's signature. */
            name: string;
            /** @description The generated value, as JSON. Any JSON type. */
            value: unknown;
        };
        /** @description A concrete, shrunken input that falsifies the property. */
        Counterexample: {
            id: components["schemas"]["CounterexampleId"];
            obligation_id: components["schemas"]["ObligationId"];
            /** @description The property text that was violated. */
            property: string;
            inputs: components["schemas"]["CounterexampleInput"][];
            /** @description What the property required, rendered for humans. */
            expected: string;
            /** @description What the code actually did, rendered for humans. */
            actual: string;
            /** @description True when the minimizer ran to a fixed point. */
            shrunk: boolean;
            shrink_steps: number;
            replay: {
                seed: string;
                /** @description Copy-pasteable command that deterministically replays this failure. */
                command: string;
            };
            created_at: components["schemas"]["Timestamp"];
        };
        ObligationTarget: {
            /** @description Function or method under obligation, `Class.method` for methods. */
            name: string;
            file: string;
            line: number;
        };
        /** @description One (function, spec) pair a run must check. Verdict-dependent fields: `verified` is non-null iff verdict is VERIFIED; `counterexample` is non-null iff verdict is FALSIFIED; `unknown_reason` is non-null iff verdict is UNKNOWN.
         *      */
        Obligation: {
            id: components["schemas"]["ObligationId"];
            run_id: components["schemas"]["RunId"];
            spec_id: components["schemas"]["SpecId"];
            target: components["schemas"]["ObligationTarget"];
            /**
             * @description Whether the target changed directly or inherited the obligation.
             * @enum {string}
             */
            source: "changed" | "blast_radius";
            verdict: components["schemas"]["Verdict"];
            verified: components["schemas"]["BoundedVerification"] | null;
            counterexample: components["schemas"]["Counterexample"] | null;
            unknown_reason: components["schemas"]["UnknownReason"] | null;
            duration_ms: number;
            created_at: components["schemas"]["Timestamp"];
        };
        /** @enum {string} */
        SpecStatus: "candidate" | "accepted" | "rejected";
        /**
         * @description Where the spec came from — mined from traces, derived statically, or proposed by a human/agent. Optional in v1 (ADR-006).
         *
         * @enum {string}
         */
        SpecProvenance: "mined" | "static" | "proposed";
        Spec: {
            id: components["schemas"]["SpecId"];
            repo_id: components["schemas"]["RepoId"];
            target: {
                name: string;
                file: string;
            };
            /** @description Spec source text. The spec DSL grammar is a G-DSL decision that has not been made; v1 treats this as opaque text and fixture bodies are non-normative placeholders.
             *      */
            body: string;
            status: components["schemas"]["SpecStatus"];
            provenance?: components["schemas"]["SpecProvenance"];
            /** @description Miner/ranker confidence. Optional in v1 (ADR-006). */
            confidence?: number;
            created_at: components["schemas"]["Timestamp"];
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Missing or invalid bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource does not exist or is not visible to the caller. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description Opaque pagination cursor from a previous response (ADR-002). */
        Cursor: string;
        /** @description Page size. */
        Limit: number;
        /** @description Run identifier. */
        RunId: components["schemas"]["RunId"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    exchangeGithubCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description GitHub OAuth authorization code. Never logged. */
                    code: string;
                };
            };
        };
        responses: {
            /** @description Token issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listRepos: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor from a previous response (ADR-002). */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of connected repositories. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Repo"][];
                        next_cursor: components["schemas"]["NextCursor"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                /** @description Filter to a single repository. */
                repo_id?: components["schemas"]["RepoId"];
                /** @description Filter by run status. */
                status?: components["schemas"]["RunStatus"];
                /** @description Opaque pagination cursor from a previous response (ADR-002). */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Run"][];
                        next_cursor: components["schemas"]["NextCursor"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    repo_id: components["schemas"]["RepoId"];
                    head_sha: components["schemas"]["GitSha"];
                    base_sha: components["schemas"]["GitSha"];
                    /** @description Present when the run is tied to a pull request. */
                    pr_number?: number;
                };
            };
        };
        responses: {
            /** @description Run accepted and queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run identifier. */
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listRunObligations: {
        parameters: {
            query?: {
                /** @description Filter by verdict. */
                verdict?: components["schemas"]["Verdict"];
                /** @description Opaque pagination cursor from a previous response (ADR-002). */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                /** @description Run identifier. */
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of obligations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Obligation"][];
                        next_cursor: components["schemas"]["NextCursor"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listSpecs: {
        parameters: {
            query?: {
                /** @description Filter to a single repository. */
                repo_id?: components["schemas"]["RepoId"];
                /** @description Filter by review status. */
                status?: components["schemas"]["SpecStatus"];
                /** @description Opaque pagination cursor from a previous response (ADR-002). */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of specs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Spec"][];
                        next_cursor: components["schemas"]["NextCursor"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
